{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 0,
   "metadata": {
    "application/vnd.databricks.v1+cell": {
     "cellMetadata": {
      "byteLimit": 10485760,
      "rowLimit": 1000
     },
     "inputWidgets": {},
     "nuid": "9402d2c6-7bd0-4b08-87a7-b8f11641b618",
     "showTitle": false,
     "tableResultSettingsMap": {},
     "title": ""
    }
   },
   "outputs": [],
   "source": [
    "-- list all tables\n",
    "SHOW TABLES;\n",
    "\n",
    "-- describe table dim_customers\n",
    "DESCRIBE TABLE dim_customers;\n",
    "\n",
    "-- list unique customer countries\n",
    "SELECT DISTINCT country\n",
    "  FROM dim_customers;\n",
    "\n",
    "\n",
    "-- list product categories, subcategories, and products\n",
    "SELECT DISTINCT\n",
    "  category,\n",
    "  subcategory,\n",
    "  product_name\n",
    "  FROM dim_products\n",
    "  ORDER BY category, subcategory, product_name;\n",
    "\n",
    "\n",
    "-- calculate total sales\n",
    "SELECT \n",
    "  SUM(sales_amount) AS total_sales\n",
    "  FROM fact_sales;\n",
    "\n",
    "-- calculate total customers\n",
    "SELECT \n",
    "  COUNT(DISTINCT customer_key) AS total_customers\n",
    "  FROM dim_customers;\n",
    "\n",
    "-- calculate total products\n",
    "SELECT\n",
    "  COUNT(DISTINCT product_key) AS total_products\n",
    "  FROM dim_products;\n",
    "\n",
    "-- calculate total orders\n",
    "SELECT\n",
    "  COUNT(DISTINCT order_number) AS total_orders\n",
    "  FROM fact_sales;\n",
    "\n",
    "\n",
    "-- calculate sales by product, sort by highest sales\n",
    "SELECT \n",
    "  p.product_name,\n",
    "  SUM(f.sales_amount) AS total_sales\n",
    "  FROM fact_sales f \n",
    "  JOIN dim_products p\n",
    "    ON f.product_key = p.product_key\n",
    "  GROUP BY p.product_name\n",
    "  ORDER BY SUM(f.sales_amount) DESC;\n",
    "\n",
    "-- calculate sales by category, sort by highest sales\n",
    "SELECT \n",
    "  p.category,\n",
    "  SUM(f.sales_amount) AS total_sales\n",
    "  FROM fact_sales f \n",
    "  JOIN dim_products p\n",
    "    ON f.product_key = p.product_key\n",
    "  GROUP BY p.category\n",
    "  ORDER BY SUM(f.sales_amount) DESC;\n",
    "\n",
    "-- calculate sales over time (month), sort chronologically\n",
    "SELECT \n",
    "  date_trunc('month', order_date) as month,\n",
    "  SUM(sales_amount) AS total_sales\n",
    "  FROM salesdb.fact_sales\n",
    "  GROUP BY month\n",
    "  ORDER BY month;\n",
    "\n",
    "\n",
    "-- calculate total profit (assuming profit = sales_amount - cost * quantity)\n",
    "SELECT \n",
    "  SUM(f.sales_amount - (p.cost * f.quantity)) AS total_profit\n",
    "  FROM fact_sales f\n",
    "  JOIN dim_products p\n",
    "    ON f.product_key = p.product_key;\n",
    "\n",
    "\n",
    "-- calculate total quantity\n",
    "SELECT \n",
    "  SUM(quantity)AS total_quantity\n",
    "  FROM fact_sales;\n",
    "\n",
    "-- calculate avg sale per customer\n",
    "SELECT \n",
    "  AVG(sales_amount) AS avg_sales\n",
    "  FROM fact_sales;\n",
    "\n",
    "\n",
    "-- calculate nr of orders by customer age group\n",
    "SELECT \n",
    "  CASE \n",
    "    -- FLOOR is used to round down the calculated age to the nearest whole number\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) BETWEEN 0 AND 18 THEN '0-18'\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) BETWEEN 19 AND 30 THEN '19-30'\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) BETWEEN 31 AND 40 THEN '31-40'\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) BETWEEN 41 AND 50 THEN '41-50'\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) BETWEEN 51 AND 60 THEN '51-60'\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) BETWEEN 61 AND 70 THEN '61-70'\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) BETWEEN 71 AND 80 THEN '71-80'\n",
    "    WHEN FLOOR(DATEDIFF(CURRENT_DATE(), c.birthdate) / 365.25) >= 81 THEN '81+'\n",
    "    ELSE 'Unknown'\n",
    "  END AS age_group,\n",
    "  COUNT(DISTINCT f.order_number) AS total_orders\n",
    "FROM workspace.salesdb.fact_sales f\n",
    "JOIN workspace.salesdb.dim_customers c\n",
    "  ON f.customer_key = c.customer_key\n",
    "GROUP BY age_group\n",
    "ORDER BY age_group;\n",
    "\n",
    "-- calculate top 10 customers by sales\n",
    "SELECT \n",
    "  c.first_name || ' ' || c.last_name AS customer,\n",
    "  SUM(f.sales_amount) AS total_sales\n",
    "  FROM fact_sales f\n",
    "  JOIN dim_customers c\n",
    "    ON f.customer_key = c.customer_key\n",
    "  GROUP BY c.first_name || ' ' || c.last_name\n",
    "  ORDER BY SUM(f.sales_amount) DESC\n",
    "  LIMIT 10;\n",
    "\n",
    "  \n"
   ]
  }
 ],
 "metadata": {
  "application/vnd.databricks.v1+notebook": {
   "computePreferences": {
    "hardware": {
     "accelerator": null,
     "gpuPoolId": null,
     "memory": null
    }
   },
   "dashboards": [],
   "environmentMetadata": null,
   "inputWidgetPreferences": null,
   "language": "sql",
   "notebookMetadata": {
    "pythonIndentUnit": 4,
    "sqlQueryOptions": {
     "applyAutoLimit": true,
     "catalog": "workspace",
     "schema": "salesdb"
    }
   },
   "notebookName": "Explore SalesDB.dbquery.ipynb",
   "widgets": {}
  },
  "language_info": {
   "name": "sql"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 0
}
